yatube/about/urls.py
from django.urls import path
from .views import AboutAuthorView, AboutTechView

app_name = 'about'

urlpatterns = [
    path('author/', AboutAuthorView.as_view(), name='author'),
    path('tech/', AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index',
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list',
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile',
    ),
    path(
        'create/',
        views.post_create,
        name='post_create',
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit',
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail',
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index',
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path(
        '',
        include('posts.urls', namespace='posts')
    ),
    path(
        'admin/',
        admin.site.urls
    ),
    path(
        'auth/',
        include('users.urls')
    ),
    path(
        'auth/',
        include('django.contrib.auth.urls')
    ),
    path(
        'about/',
        include('about.urls', namespace='about')
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.models import CreatedModel
from django.db.models import UniqueConstraint

POSTS_PER_PAGE = 10

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Название группы',
        help_text='Введите название группы',
        max_length=200,
    )
    slug = models.SlugField(
        'Слаг группы',
        unique=True,
    )
    description = models.TextField(
        'Описание',
        help_text='Укажите описание группы',
    )

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(CreatedModel):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name='Автор',
        related_name='posts',
        null=True,
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        verbose_name='Группа',
        related_name='posts',
        blank=True,
        null=True,
        help_text='Группа, к которой будет относиться пост',

    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    def __str__(self):
        return self.text[:15]

    class Meta(CreatedModel.Meta):
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Комментарий',
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments',
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Напишите комментарий',
    )

    class Meta(CreatedModel.Meta):
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='following',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

        constraints = (
            UniqueConstraint(
                fields=['user', 'author'],
                name='unique_following'
            ),
        )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'text',
            'group',
            'image',
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'text',
        )

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.views.decorators.cache import cache_page

from .models import Post, Group, User, Follow, POSTS_PER_PAGE
from .forms import PostForm, CommentForm

CACHE_TIMEOUT = 20 * 60
PRETEXT_LENGTH = 30


@cache_page(CACHE_TIMEOUT, key_prefix='index_page')
def index(request: HttpRequest) -> HttpResponse:
    """
    View for index page.
    """
    posts = Post.objects.all()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_obj = paginator.get_page(request.GET.get('page'))
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request: HttpRequest, slug: str) -> HttpResponse:
    """
    View for group pages. Posts related to a specific group are here.
    """
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_obj = paginator.get_page(request.GET.get('page'))
    context = {
        'title': f'Записи сообщества {group.title}',
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request: HttpRequest, username: str) -> HttpResponse:
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)
    is_follow_visible = (request.user.is_authenticated
                         and request.user != author)
    following = (is_follow_visible
                 and Follow.objects.filter(user=request.user,
                                           author=author).exists())
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_obj = paginator.get_page(request.GET.get('page'), )
    context = {
        'author': author,
        'full_name': f'{author.first_name} {author.last_name}',
        'posts_count': posts.count(),
        'page_obj': page_obj,
        'following': following,
        'is_follow_visible': is_follow_visible,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_id)
    posts_count = Post.objects.filter(
        author=post.author
    ).count()
    context = {
        'pretext': post.text[:PRETEXT_LENGTH],
        'post': post,
        'posts_count': posts_count,
        'form': CommentForm(request.POST or None),
        'comments': post.comments.all(),
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request: HttpRequest) -> HttpResponse:
    post_form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    context = {
        'title': 'Добавить запись',
        'submit': 'Добавить',
        'form': post_form
    }

    if not post_form.is_valid():
        return render(request, 'posts/create_post.html', context)

    post_instance = post_form.save(commit=False)
    post_instance.author = request.user
    post_instance.save()

    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_id)
    if post.author.pk != request.user.pk:
        return redirect('posts:post_detail', post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    context = {
        'title': 'Изменить запись',
        'submit': 'Сохранить',
        'form': form
    }

    if not form.is_valid():
        return render(request, 'posts/create_post.html', context)

    form.save()
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request: HttpRequest) -> HttpResponse:
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_obj = paginator.get_page(request.GET.get('page'))
    return render(request, 'posts/follow.html', {'page_obj': page_obj})


@login_required
def profile_follow(request, username: str) -> HttpResponse:
    author = get_object_or_404(User, username=username)
    is_followed = Follow.objects.filter(
        user=request.user, author=author
    ).exists()
    if request.user != author and not is_followed:
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username: str) -> HttpResponse:
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    Создание нового поста
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {{ field }}
                                {% if field.help_text %}
                                    <small
                                            id="{{ field.id_for_label }}-help"
                                            class="form-text text-muted"
                                    >
                                        {{ field.help_text|safe }}
                                    </small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {{ submit }}
                            </button>
                        </div>
                    </form>
                </div> <!-- card body -->
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Подписки на авторов{% endblock %}
{% block content %}
    <div class="container py-5">
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
            {% include 'posts/includes/post_list.html' %}
            {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                    все записи группы
                </a>
            {% endif %}
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>
            {{ group.description }}
        </p>
        {% for post in page_obj %}
            {% include 'posts/includes/post_list.html' %}
            {% if request.user == post.author %}
                <a href="{% url 'posts:post_edit' post.pk %}">
                    изменить пост
                </a>
            {% endif %}
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}

        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
    {{ 'Последние обновления на сайте' }}
{% endblock %}
{% block content %}
    <div class="container py-5">
        {% include 'posts/includes/switcher.html' %}
        <h1>Последние обновления на сайте</h1>
        {% for post in page_obj %}
            {% include 'posts/includes/post_list.html' %}
            {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}
                <hr>{% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Пост {{ pretext }}
{% endblock %}
{% block content %}
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                {% if post.group %}
                    <li class="list-group-item">
                        Группа: {{ post.group }}
                        <br>
                        {% if post.group %}
                            <a href="{% url 'posts:group_list' post.group.slug %}">все
                                записи группы</a>
                        {% endif %}
                    </li>
                {% endif %}
                <li class="list-group-item">
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора: <span>{{ posts_count }}</span>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' post.pk %}">
                        все посты пользователя
                    </a>
                </li>
                <br>
                {% if request.user == post.author %}
                    <li class="list-group-item">
                        <a href="{% url 'posts:post_edit' post.pk %}">
                            изменить пост
                        </a>
                    </li>
                {% endif %}
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
                {{ post.text }}
            </p>
        </article>
        {% include 'includes/comments.html' %}
    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{ full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ posts_count }}</h3>
      {% if is_follow_visible %}
        {% if following %}
          <a
                  class="btn btn-lg btn-light"
                  href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
                  class="btn btn-lg btn-primary"
                  href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
    </div>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>

      {% if request.user == post.author %}
        <a href="{% url 'posts:post_edit' post.pk %}">
          изменить пост
        </a>
      {% endif %}

      <br>

      <a href="{% url 'posts:post_detail' post.pk %}">подробная
        информация </a>

      <br>

      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все
          записи группы</a>
      {% endif %}

      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}

    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}